version: "3.8"

services:
  api:
    # image: "fastapi_starter:1.0.0"
    container_name: FatAPI
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/usr/src/app/app:cached
      - ./backend/db:/usr/src/app/db:cached
      - ./backend/scripts:/usr/src/app:cached
    # working_dir: /usr/src/app/scripts
    command: bash -c "run.sh"
    networks:
      - frontend_network
      - backend_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - ./backend/.env.dev
      
  db:
    # image: "fastapi_starter_db:1.0.0"
    container_name: MySQL
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./backend/docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./backend/docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./backend/log/db:/var/log/mysql:cached
    networks:
      - backend_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - ./backend/.env.dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./backend/.env.dev
    links:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./backend/phpmyadmin/sessions:/sessions
    networks:
      - backend_network

  front:
    container_name: Node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend_network

networks:
  # default:
  #   external:
  #     name: bridge
  frontend_network:
    name: frontend_network
    driver: bridge
    # external: true
  backend_network:
    name: backend_network
    driver: bridge
    # external: true